### PR TITLE
Updates for CakePHP 4

### PR DESCRIPTION
**Pull request by BGehrels**
Based on the test- and documentation updates of @dorxy, thanks a lot for that!

Changes:
- `ErrorHandlerMiddleware:`
  - In Cake 3, Cakes `ErrorHandlerMiddleware` logged directly to the `Log`. In order to get the `Request` and the `Exception` object handed down to the `SentryLog`, this class was overridden.
  - Cake4's `ErrorHandlerMiddleware` delegates logging to the `ErrorHandler` and passes the `Request` and the `Exception` object to the `ErrorHandler` itself. So the customization of the middleware became obsolete - and therefore also it's initialization in the `Plugin`
- `ErrorHandler`
  - `logException()`-method
    - In CakePHP 3, Cakes `ErrorHandler` logged directly to the `Log`. In order to get the the `Exception` object handed down to the `SentryLog? , this method was overridden.
    - In Cake4 `ErrorHandler` delegates logging to the `ErrorLogger` and passes the `Exception` object to the `ErrorLogger`. So the customization of this method became obsolete.
  - `logError()`-method
    - For CakePHP3, you customized this method: It wrapped the error into an `Exception` and then delegated that to `logException()`
    - I could not see why you did this, and since i'm afraid to break something i decided to keep it that way.
    - so `logErrror()` now wraps and delegates to `logException` which delegated to `ErrorLogger`.
- `ErrorLogger`
  - The CakePHP 4 `ErrorLogger` generates a message from the `Exception` and the `Request` and passes that to the `Log`. the original `Exception` and `Request` classes are thrown away.
  - Since we want them to be present in the `SentryLog`, we override this class and add them to the log context.

Works fine in production for us

### CODE REVIEW

**Comment by BGehrels** [comment]
Please also keep in  mind that @dorxy 's insights on Plugin bootstrapping order still hold true: https://github.com/Connehito/cake-sentry/pull/29#issuecomment-579144308

**Comment by o0h** [comment]
Thank you for getting to work !! 👍 
I've just skimmed it, but I'll take a moment to go over the details later, so please be patient.

**Comment by o0h** [comment]
I think it's better to include `test_app` and its Docker environment in this plugin so that plugin developers can work easily.
I'm going to use this PR to develop the master branch first, and then I'll create another PR as my work to revive test_app😄.

**Comment by o0h** [comment]
I created a new branch of "3.x" to work on CakePHP4 and changed the base branch of this PR to it.
When all CakePHP4 support is complete and ready for release, the new branch "3.x" will be merged into master.

**Comment by o0h** [comment]
https://github.com/Connehito/cake-sentry/pull/34#issuecomment-625242666

I've been able to confirm it myself." The "plugin load" command seems to have a problem with the loading order.
I'm going to update the README in #36 .

**Comment by dorxy** [comment]
Good to see such activity for the upgrade! Glad to be able to help 😊

**Comment by BGehrels** [comment]
Fixed a few of your points.

Regarding the plugin load order issue mentioned by @dorxy in https://github.com/Connehito/cake-sentry/pull/29#issuecomment-579144308 : Maybe this could be fixed by moving the Plugin configuration step from the `bootstrap.php` (automatic) to the app.php (manual, via a "Getting started" section in the `Readme.md`)

**Comment by o0h** [comment]
@BGehrels  Thank you for all your hard work! (and of course @dorxy )

> Regarding the plugin load order issue mentioned by @dorxy in #29 (comment)

Yes, I think you make a good point.
There are a few things I want to try and think about, so I'm going to tackle them in a separate PR
https://github.com/Connehito/cake-sentry/issues/36#issuecomment-626254600

**Pull request merged**
